# Generated by Django 5.0.2 on 2024-02-10 10:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_operation_sys', '0003_remove_student_classes_remove_teacher_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule', to='school_operation_sys.class')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule', to='school_operation_sys.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule', to='school_operation_sys.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade', to='school_operation_sys.student')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule', to='school_operation_sys.schedule')),
            ],
        ),
    ]
