# Generated by Django 5.0.2 on 2024-02-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_operation_sys', '0004_schedule_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
